### ISSUE TITLE
login credentials / mongodb schema / how to run?

### ISSUE THREAD

**Issue by hopfi2k** [rohittiwari-dev/ocpp-ts-rpc#1]
Sorry, my fault

**Comment by rohittiwari-dev** [comment]
@hopfi2k Thanks for your consideration to the project, after understanding your query, i would like you to inform you that this is like a framework which helps to create and connect to EV chargers this package wraps on WebSocket helps communicate over OCPP protocol based ocpp1.6 and ocpp2.0.1 and can more of after some modifications Yes to run this readme is not ready yet working on it but you can refer to https://www.npmjs.com/package/ocpp-rpc , this project implement this package with typescript   it will have same implementation with typescript as owner of ocpp-rpc package is not comfortable with typescript inclusion that problem this project is fixing thank you. consider using that package if you are javascript developer and do support https://github.com/mikuso owner of ocpp-rpc package , and this project by me helps typescript developer who was not able to use that package
